#!/usr/bin/env sh

REVISION=${BUILD_NUMBER:-'DEV'}

banner() {
  echo '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'
  echo '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'
  echo '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'
  echo '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'
  echo '%%%%    '$1
  echo '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'
  echo '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'
  echo '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'
  echo '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'
}

clean() {
  cd online

  rm -rf dist || exit $?
  rm -rf node_modules || exit $?
  rm -rf serve/modules || exit $?
  rm -rf serve/app/classic/resources || exit $?
}

# Sync the shape resources that online bundles, from core.
#
# These used to be a hand-maintained copy, checked in under
# online/src/worker/legacy/resources.  Nobody remembered to repeat the copy when
# core gained or renamed a shape, so the two trees drifted.  The tree is now
# generated here and gitignored; core is the single source of truth.
#
# Only .vef is copied.  The .vZome design sources and the legacy .zomic exports
# that sit beside them in core are historic, never loaded by online, and stay in
# core, where the three formats remain together as a lineage.
#
# The .vef files are imported as URLs and bundled by esbuild (loader '.vef':
# 'dataurl'), so each directory also needs an index.js naming its shapes, and a
# top-level index.js mapping shape-package names to those modules.  Both are
# generated below.
syncShapeResources() {
  banner 'Syncing shape resources from core'

  core_parts=../core/src/main/resources/com/vzome/core/parts
  core_symm=../core/src/main/resources/com/vzome/core/math/symmetry
  dest=src/worker/legacy/resources/com/vzome/core

  rm -rf $dest || exit $?
  mkdir -p $dest/parts $dest/math/symmetry || exit $?

  # Copy the .vef files, preserving core's directory structure.
  ( cd $core_parts && find . -name '*.vef' -type f -print ) \
  | sed 's|^\./||' \
  | while read -r f; do
      mkdir -p "$dest/parts/$( dirname "$f" )" || exit $?
      cp "$core_parts/$f" "$dest/parts/$f" || exit $?
    done
  cp $core_symm/*.vef $dest/math/symmetry || exit $?

  # A per-directory index.js for each shape package, importing every .vef in it.
  # Shape names are not always valid JS identifiers (e.g. "green-short"), so the
  # import bindings are camelCased while the map keys stay verbatim -- the keys
  # are what ExportedVEFShapes asks for.
  ( cd $dest/parts && find . -name '*.vef' -exec dirname {} \; | sed 's|^\./||' | sort -u ) \
  | while read -r pkg; do
      ( cd "$dest/parts/$pkg" || exit $?
        echo '// Generated by cicd/online.bash -- do not edit.'
        echo '// The .vef imports resolve to URLs via the esbuild dataurl loader.'
        echo
        for vef in *.vef; do
          name=${vef%.vef}
          ident=$( echo "$name" | awk -F- '{ printf "%s", $1; for(i=2;i<=NF;i++) printf "%s%s", toupper(substr($i,1,1)), substr($i,2) }' )
          echo "import ${ident}Url from './${name}.vef'"
        done
        echo
        echo 'const shapes = {'
        for vef in *.vef; do
          name=${vef%.vef}
          ident=$( echo "$name" | awk -F- '{ printf "%s", $1; for(i=2;i<=NF;i++) printf "%s%s", toupper(substr($i,1,1)), substr($i,2) }' )
          echo "  '${name}': ${ident}Url,"
        done
        echo '}'
        echo
        echo 'export default shapes' ) > "$dest/parts/$pkg/index.js" || exit $?
    done

  # The top-level index.js, mapping each shape-package name to its module.  The
  # keys must be the legacy Java package names, since that is what
  # ExportedVEFShapes asks the ResourceLoader for, so nested packages keep their
  # "/" (e.g. 'heptagon/antiprism', 'sqrtPhi/zome').
  ( cd $dest/parts || exit $?
    echo '// Generated by cicd/online.bash -- do not edit.'
    echo
    pkgs=$( find . -name '*.vef' -exec dirname {} \; | sed 's|^\./||' | sort -u )
    # 'default' is a shape package name and a JS reserved word, so every binding
    # is suffixed to keep the generated identifiers legal.
    for pkg in $pkgs; do
      ident=$( echo "$pkg" | awk -F/ '{ printf "%s", $1; for(i=2;i<=NF;i++) printf "%s%s", toupper(substr($i,1,1)), substr($i,2) }' )
      echo "import ${ident}Shapes from './${pkg}/index.js'"
    done
    echo
    echo 'const shapes = {'
    for pkg in $pkgs; do
      ident=$( echo "$pkg" | awk -F/ '{ printf "%s", $1; for(i=2;i<=NF;i++) printf "%s%s", toupper(substr($i,1,1)), substr($i,2) }' )
      echo "  '${pkg}': ${ident}Shapes,"
    done
    echo '}'
    echo
    echo 'export default shapes' ) > "$dest/parts/index.js" || exit $?

  # The symmetry group resources (quaternionic roots) are indexed the same way.
  ( cd $dest/math/symmetry || exit $?
    echo '// Generated by cicd/online.bash -- do not edit.'
    echo
    for vef in *.vef; do
      name=${vef%.vef}
      ident=$( echo "$name" | awk -F- '{ printf "%s", $1; for(i=2;i<=NF;i++) printf "%s%s", toupper(substr($i,1,1)), substr($i,2) }' )
      echo "import ${ident}Url from './${name}.vef'"
    done
    echo
    echo 'const resources = {'
    for vef in *.vef; do
      name=${vef%.vef}
      ident=$( echo "$name" | awk -F- '{ printf "%s", $1; for(i=2;i<=NF;i++) printf "%s%s", toupper(substr($i,1,1)), substr($i,2) }' )
      echo "  '${name}': ${ident}Url,"
    done
    echo '}'
    echo
    echo 'export default resources' ) > "$dest/math/symmetry/index.js" || exit $?
}

marshallResources() {
  banner 'Marshalling core and desktop resources'
  # Remove the detritus of earlier builds (& dev server)
  rm -rf serve/modules || exit $?
  rm -rf serve/app/classic/resources || exit $?
  # Marshall the resources from core and desktop
  mkdir -p serve/app/classic/resources/com/vzome/core/exporters || exit $?
  cp -R ../desktop/src/main/resources/* serve/app/classic/resources || exit $?
  cp -R ../core/src/main/resources/com/vzome/core/exporters/* serve/app/classic/resources/com/vzome/core/exporters || exit $?
  # marshall models for the inspector app
  mkdir -p serve/app/inspector/models
  cp serve/app/models/* serve/app/inspector/models
}

generateRevisionJs() {
  banner 'Generating src/revision.js'
  echo "export const REVISION=\"${REVISION}\";" > src/revision.js
  echo "export const importLegacy = async () => import( './worker/legacy/dynamic.js' );" >> src/revision.js
  echo "export const importZomic = async () => import( './worker/legacy/zomic/index.js' );" >> src/revision.js

  # index exporter resources
  ( cd serve/app/classic/resources
    echo 'export const resourceIndex = ['
    find com/vzome/core/exporters -type f -exec echo "  \"{}\"", \;
    echo ' ];' ) >> src/revision.js
}

installJsDependencies(){
  banner 'Preparing the distribution folder with Yarn'
  yarn install || exit $?
}

buildForProduction() {
  installJsDependencies || exit $?

  rm -rf dist || exit $?
  yarn run build || exit $?

  cd dist

  banner 'Creating the online.tgz archive'
  cp -R ../serve/app/* app && \
    rm -rf app/test* && \
    echo 'Header always set Access-Control-Allow-Origin "*"' > modules/.htaccess && \
    echo ${REVISION} > modules/revision.txt && \
    tar czvf online.tgz app modules
}

initJs(){
  cd online

  syncShapeResources || exit $?

  marshallResources || exit $?

  generateRevisionJs || exit $?

  installJsDependencies || exit $?
}

devJs(){
  initJs || exit $?

  yarn run dev
}

productionBuild(){
  cd online

  syncShapeResources || exit $?

  marshallResources || exit $?

  generateRevisionJs || exit $?

  buildForProduction || exit $?

  banner 'Production build available in online/dist and online/dist/online.tgz'
}


case $1 in

  init)
    initJs
    ;;

  quickstart)
    devJs
    ;;

  dev)
    devJs
    ;;

  prod)
    productionBuild
    ;;

  clean)
    clean
    ;;

  *)
    banner 'no command (dev|prod|clean) provided'
    ;;
esac


