# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: vZome Online build

on:
  workflow_dispatch:
    inputs:
      doDeploy:
        type: boolean
        description: 'Deploy to Dreamhost'     
        required: true

env:
  BUILD_NUMBER: ${{ github.run_number }}
  GIT_COMMIT: ${{ github.sha }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.3.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Grant execute permissions
      run: chmod +x gradlew cicd/build-online.bash
    - name: Build with Gradle and Yarn
      run: cicd/build-online.bash
    - name: Archive vZome Online build
      uses: actions/upload-artifact@v2
      with:
        name: online-app
        path: online/dist/online.tgz

  deploy:
    needs: build
    if: github.event.inputs.doDeploy
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Download the vZome Online build
        uses: actions/download-artifact@v2
        with:
          name: online-app
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.DREAMHOST_USER }}
          server: ${{ secrets.DREAMHOST_FQDN }}
          ssh_private_key: ${{ secrets.DREAMHOST_SSH_PRIVATE_KEY }} 
          local_path: 'online.tgz'
          remote_path: 'vzome.com'
